#!/usr/bin/env sh

# Spacebar setting
# spacebar -m config status_bar                   on

#2020-12-7改

# spacebar -m config status_bar_text_font         "Helvetica Neue:Bold:20.0"
# spacebar -m config status_bar_icon_font         "Font Awesome 5 Free:Solid:12.0"
# spacebar -m config status_bar_background_color  0xf0202020
# spacebar -m config status_bar_foreground_color  0xf0a8a8a8
# # spacebar -m config status_bar_space_icon_strip           
# spacebar -m config status_bar_space_icon_strip           
# spacebar -m config status_bar_power_icon_strip   
# spacebar -m config status_bar_space_icon        
# spacebar -m config status_bar_clock_icon        
# spacebar -m config status_bar_clock_format      "%A %d %B %R"


spacebar -m config position           bottom
spacebar -m config height             50
spacebar -m config spacing_left       25
spacebar -m config spacing_right      15
spacebar -m config text_font          "Helvetica Neue:Bold:12.0"
spacebar -m config icon_font          "Font Awesome 5 Free:Solid:12.0"
# spacebar -m config background_color   0xff202020
spacebar -m config background_color   0xff000000
spacebar -m config foreground_color   0xffa8a8a8
spacebar -m config space_icon_color   0xff8B814C
spacebar -m config power_icon_color   0xffcd950c
spacebar -m config battery_icon_color 0xffd75f5f
spacebar -m config dnd_icon_color     0xffa8a8a8
spacebar -m config clock_icon_color   0xffa8a8a8
spacebar -m config space_icon_strip            
spacebar -m config power_icon_strip    
spacebar -m config space_icon         
spacebar -m config clock_icon         
spacebar -m config dnd_icon           
spacebar -m config clock_format       "%a %y/%m/%d %R"
