#!/usr/bin/env sh

# Spacebar setting
# spacebar -m config status_bar                   on
spacebar -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
spacebar -m config status_bar_icon_font         "Font Awesome 5 Free:Solid:12.0"
spacebar -m config status_bar_background_color  0xf0202020
spacebar -m config status_bar_foreground_color  0xf0a8a8a8
spacebar -m config status_bar_space_icon_strip     4 5 6 7 8 9 10
spacebar -m config status_bar_power_icon_strip   
spacebar -m config status_bar_space_icon        
spacebar -m config status_bar_clock_icon        
spacebar -m config status_bar_clock_format      "%A %d %B %R"